### ISSUE TITLE
Current climate status

### ISSUE THREAD

**Issue by dehret** [thomasddn/ha-volvo-cars#2]
First of all thanks a lot for creating this integration, it is super helpful and working great for me 👍

Is there a way to get the current climate status using this integration?

My use case is to start climatization of the car using a physical button before leaving the house. There are actions to start and stop climatization, and they do work. However, I'd like to read out the current climatization state such that I can show some feedback on the button LED whether the car has actually received the command and is currently starting A/C. If I have to check in the app whether it has worked, then I'm actually better off just using the app anyway.

Do you have any idea on whether this is possible with the API you are using?

Cheers, Dominik

**Comment by thomasddn** [comment]
Hi,

Thank you for the appreciation!

With the API, there is only the option to start or stop the climatization. There is nothing to read the current climatization state.

I could have a sensor based on which button you've pushed, but that would be a bit wonky. How do I know if the climatization has been stopped? The car could stop the climatization because the temperature is on point, or you are leaving early, or you have stopped the climatization by using the Volvo app.

To circumvent this, the result of the button (and for locks too) is added to the entity attributes, together with a timestamp. The list of possible values is: running, waiting, completed, rejected, unknown, timeout, connection_failure, vehicle_in_sleep, delivered, car_error, not_allowed_privacy_enabled, not_allowed_wrong_usage_mode.

This attribute still doesn't guarantee if the climatization is (still) running, but you can know if the command succeeded or not.

Is this feasible for you? Or if you have suggestions, please share them!

**Comment by dehret** [comment]
I'm not familiar with the Volvo Connected Vehicle API to be honest. I just assumed that there's a state available that can be queried to get the current climate state.

If you use the Volvo app, for example, it will show the correct a/c state even if the command was triggered by your HA plugin. 

Did I understand it right that there is no such API available to get the status? You can only find out the status by actually starting or stopping AC and then interpreting the response of this request?

**Comment by thomasddn** [comment]
Correct, the API does not provide any way the get the current actual state of the climatization.

I know the Volvo app does show the actual state, but unfortunately this is not possible with the API.

There are more things that the Volvo app can do which are not possible with the API, such as setting the target SoC and scheduling climatization.

**Comment by dehret** [comment]
I see. I'll make use of the `Last result` attribute then. Will map "completed" and "running" to the success state. Will reset it automatically after - say 10 mins or so - or when the stop action has completed successfully.

Will report back if this is working reliably enough in a few days :)

**Comment by thomasddn** [comment]
I'm closing this issue. Reopen it if you don't like the outcome of your testing.

**Comment by thomasddn** [comment]
See discussion #17

**Comment by krfr** [comment]
At https://developer.volvocars.com/apis/connected-vehicle/v2/endpoints/climate/#start-climatisation it seems to be a function called "Response body" and invokeStatus. 
Is it possible to get invokeStatus response implemented?

**Comment by thomasddn** [comment]
You can find the response in the attribute of the button, as outlined in the readme. 😉

**Comment by thomasddn** [comment]
The lock status is returned by the API. So even if you lock or unlock your car with the app or with your keys, the entity will show the correct state.

Showing a state based on some attribute or based on the latest action, is just an assumption. It would not reflect the actual state. Therefore I prefer not to add such an entity. Other users will then complain it is showing a wrong value.

You can always create a template sensor to show the state.

**Comment by krfr** [comment]
Ah, I understand.
I have already created at sensor, so i use that right now.

**Comment by Gilles2senior** [comment]
@dehret , would you mind sharing the template you have implemented for the climate start/stop to report status using the attribute please? Would love to test it as well without re-inventing it all. Thanks

**Comment by Rajackar** [comment]
@dehret , I'd be very interested as well. I wonder how the official app does this. Since it does update the status in the app when I change it through home assistant or directly on the API.
